fetch: create genre calls from API
LucasAlt40/Apollo_Project pull request #17
Opened 2024-04-04 03:59 UTC by gutsserrano

In this branch as created all methods to get the genres and save them in the GenreDAO

2024-04-05 22:24 UTC, LucasAlt40 requested changes
It seems good, just remove the comments and it's done.

2024-04-05 22:24 UTC, LucasAlt40 commented on src/main/java/com/apollo/model/service/GenreService.java
> +            retorno = objectMapper.readValue(response, ResponseGenreDto.class);
Variable in portuguese

2024-04-05 22:24 UTC, LucasAlt40 commented on src/main/java/com/apollo/model/service/GenreService.java
> +            // show saved Genres in DAO
It's best to remove these comments as they don't add anything

2024-04-05 22:24 UTC, LucasAlt40 commented on src/main/java/com/apollo/model/service/GenreService.java
> +//        }  catch (Exception e) {
Same thing here.

2024-04-06 00:34 UTC, gutsserrano commented on src/main/java/com/apollo/model/service/GenreService.java
> +            // show saved Genres in DAO
Ok.

2024-04-06 00:35 UTC, gutsserrano commented on src/main/java/com/apollo/model/service/GenreService.java
> +//        }  catch (Exception e) {
Ok.

2024-04-06 00:35 UTC, gutsserrano commented on src/main/java/com/apollo/model/service/GenreService.java
> +            retorno = objectMapper.readValue(response, ResponseGenreDto.class);
I will change to ResponseGenreDto. Thanks!

2024-04-06 03:13 UTC, LucasAlt40 approved these changes

2024-04-06 03:13 UTC, merged